"""add_agree_disagree_and_post_agreements

Revision ID: b374b5e240d3
Revises: 589d2d2b5606
Create Date: 2026-07-30 15:18:25.199275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b374b5e240d3'
down_revision: Union[str, Sequence[str], None] = '589d2d2b5606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_agreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_agreement_post_user')
    )
    op.create_index(op.f('ix_post_agreements_id'), 'post_agreements', ['id'], unique=False)
    op.add_column('posts', sa.Column('agree_count', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('disagree_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'disagree_count')
    op.drop_column('posts', 'agree_count')
    op.drop_index(op.f('ix_post_agreements_id'), table_name='post_agreements')
    op.drop_table('post_agreements')
    # ### end Alembic commands ###
