"""add_wallet_address_and_tx_status

Revision ID: c57028d8928b
Revises: f099a62218f0
Create Date: 2026-08-07 15:01:53.656204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57028d8928b'
down_revision: Union[str, Sequence[str], None] = 'f099a62218f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_transactions', sa.Column('status', sa.String(), nullable=False))
    op.add_column('users', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_address')
    op.drop_column('token_transactions', 'status')
    # ### end Alembic commands ###
