"""add_desci_columns_and_tables

Revision ID: f099a62218f0
Revises: b374b5e240d3
Create Date: 2026-08-06 13:03:06.164345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f099a62218f0'
down_revision: Union[str, Sequence[str], None] = 'b374b5e240d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Mevcut satırlar için server_default ile NOT NULL sütunlar ekleniyor
    op.add_column('post_comments', sa.Column('agree_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('is_rare_case', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('posts', sa.Column('rare_vote_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('posts', sa.Column('validation_count', sa.Integer(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'validation_count')
    op.drop_column('posts', 'rare_vote_count')
    op.drop_column('posts', 'is_rare_case')
    op.drop_column('post_comments', 'agree_count')
    # ### end Alembic commands ###
